spring:
  cloud:
    config:
      server:
        port: 8081
        git:
          default-label: config-server
          uri: https://github.com/Almg-star/microservicios-tutorial.git
          search-paths: config-data
          application:
            name: config-service
